### Task 1: Creating NumPy Arrays
### 1. Import NumPy as np.
### 2. Create the following arrays:
### A 1D array of integers from 1 to 10
### A 2D array of shape (3, 3) with values from 1 to 9
### A NumPy array from the list: [10, 20, 30, 40, 50]
### 3. Print:
### Shape of each array
### Data type of each array

In [1]:
import numpy as np

In [2]:
array1=np.arange(1,11)

In [4]:
array1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
array2=np.arange(1,10).reshape(3,3)

In [6]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
array3=np.array([10, 20, 30, 40, 50])

In [26]:
print("shapes of arrays")
one=(array1).shape
two=(array2).shape
three=(array3).shape
one_dtype=(array1).dtype
two_dtype=(array2).dtype
three_dtype=(array3).dtype
print(f"1st is {one} and data type is {one_dtype} \n 2nd is {two} and data type is {two_dtype} \n 3rd is {three} and data type is {three_dtype}")

shapes of arrays
1st is (10,) and data type is int64 
 2nd is (3, 3) and data type is int64 
 3rd is (5,) and data type is int64


### Task 2: Important Mathematical Operations
### Given two arrays:
### A = np.array([10, 20, 30, 40])
### B = np.array([1, 2, 3, 4])
### Perform and print results for:
### 1. Addition (A + B)
### 2. Subtraction (A - B)
### 3. Multiplication (A + B)
### 4. Division (A/B)
### 5. Power (A ** 2)
### Extra (optional): Use NumPy functions: np.add(), np.subtract() for the same operations.


In [28]:
A = np.array([10, 20, 30, 40])
B = np.array([1, 2, 3, 4])

In [39]:
add=np.add(A,B)
sub=np.subtract(A,B)
mul=A*B
div=A/B
power=A**2

In [40]:
print(f"Addition : {add}")
print(f"Subtraction : {sub}")
print(f"Multiplication : {mul}")
print(f"Division : {div}")
print(f"Power : {power}")

Addition : [11 22 33 44]
Subtraction : [ 9 18 27 36]
Multiplication : [ 10  40  90 160]
Division : [10. 10. 10. 10.]
Power : [ 100  400  900 1600]


### Task 3: Important NumPy Mathematical Formulas
### Given:
### values = np.array([2, 4, 6, 8, 10])
### Calculate:
### 1. Square root of each element
### 2. Exponential of each element
### 3. Natural logarithm of each element
### 4. Sum of all elements
### 5. Cumulative sum of elements
### Use NumPy functions only.

In [42]:
values = np.array([2, 4, 6, 8, 10])

In [44]:
square_root=np.sqrt(values)
exp= np.exp(values)
log=np.log(values)
sums=np.sum(values)
cumsum=np.cumsum(values)


In [45]:
print("Square Root:", square_root)
print("Exponential:", exp)
print("Natural Log:", log)
print("Sum:", sums)
print("Cumulative Sum:", cumsum)

Square Root: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Natural Log: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
Sum: 30
Cumulative Sum: [ 2  6 12 20 30]


### Task 4: Aggregation Operations
### Given a 2D array:
### data = np.array([ [10, 20, 30], [40, 50, 60], [70, 80, 90] ])
### Find:
### 1. Row-wise sum
### 2. Column-wise sum
### 3. Minimum value
### 4. Maximum value
### 5. Overall mean

In [47]:
data = np.array([ [10, 20, 30], [40, 50, 60], [70, 80, 90] ])
data

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [51]:
row=np.sum(data, axis=1)
row

array([ 60, 150, 240])

In [54]:
col=np.sum(data, axis=0)
col

array([120, 150, 180])

In [55]:
minimum=np.min(data)
minimum

np.int64(10)

In [57]:
maximum=np.max(data)
maximum

np.int64(90)

In [58]:
mean=np.mean(data)
mean

np.float64(50.0)

### Task 5: Statistical Operations (Core Focus)
### Given:
### marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
### Calculate and print:
### 1. Mean
### 2. Median
### 3. Variance
### 4. Standard Deviation
### 5. Minimum & Maximum
### 6. Range (max - min)

In [60]:
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])

In [62]:
mean_v=np.mean(marks)
median_v=np.median(marks)
variance_v=np.var(marks)
standard=np.std(marks)
min_v=np.min(marks)
max_v=np.max(marks)
range_v=max_v - min_v

print(f"1. Mean: {mean_v}")
print(f"2. Median: {median_v}")
print(f"3. Variance: {variance_v}")
print(f"4. Standard Deviation: {standard}")
print(f"5. Minimum: {min_v}, Maximum: {max_v}")
print(f"6. Range: {range_v}")

1. Mean: 79.25
2. Median: 81.5
3. Variance: 134.1875
4. Standard Deviation: 11.583932838203095
5. Minimum: 60, Maximum: 95
6. Range: 35


### Task 6: Percentiles & Sorting
### Using the same marks array:
### 1. Sort the array
### 2. Find:
### 25th percentile
### 50th percentile
### 75th percentile
### 3. Count how many students scored above the average marks

In [65]:
sort=np.sort(marks)
one=np.percentile(marks, 25)
two=np.percentile(marks, 50)
three=np.percentile(marks, 75)

avg=np.mean(marks)
count=np.sum(marks> avg)

print("Sorted Marks:", sort)
print("25th Percentile:", one)
print("50th Percentile (Median):", two)
print("75th Percentile:", three)

print("Average Marks:", avg)
print("Students scoring above average:", count)

Sorted Marks: [60 66 72 78 85 88 90 95]
25th Percentile: 70.5
50th Percentile (Median): 81.5
75th Percentile: 88.5
Average Marks: 79.25
Students scoring above average: 4


### Task 7: Mini Use Case: Sales Analysis
### Given daily sales data: sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
### Perform:
### 1. Total weekly sales
### 2. Average daily sales
### 3. Highest and lowest sales day
### 4. Standard deviation of sales
### 5. Identify days where sales were above average

In [68]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])

In [70]:
total=np.sum(sales)
average=np.mean(sales)
high=np.max(sales)
low=np.min(sales)
std_dev=np.std(sales)
days=np.where(sales > average)[0]
print(f"Total: {total}")
print(f"Average: {average:.2f}")
print(f"Highest: {high}, Lowest: {low}")
print(f"Std Dev: {std_dev:.2f}")
print(f"Days above average (indices): {days}")

Total: 10700
Average: 1528.57
Highest: 2000, Lowest: 900
Std Dev: 345.23
Days above average (indices): [3 4 5 6]
