## Numpy

### Numpy is fundamental package for scientific computing in python. 
### It is a python library that provides multi dimentional array object and various derived objects such as masked arrays or matrices and an assortment of routines for fast operations on arrays including Mathematical, logical, shape manipulation, sortng, selecting, I/O, Discrete Fourier Transform, Basic linear algebra, Statical Operations, Random Simulation, etc.
### At the core of the numpy package is the n-dimentional array objects.


In [ ]:
## Why Numpy?
### 2008-09, Data science ->matlab, R language, 
### Data types in python -> list, Dictionary -> are slow
### Syntax -> python -> easy
### We need speed and leass memory to work with the huge amount of data.

#### Numpy -> c language -> wrapped -> python language
### -> Numpy -> syntax -> Easy for beginners -> Performing scientific calculations -> creating Multi Dimentional arrays -> speed is faster for applying operations -> less Memory 

### Libraries like scikit learn, Tensorflow and Pytorch require input data in numpy arrays or Tensors.


## Numpy arrays vs Python Sequences
### Numpy Arrays have fix size at creation, unlike python lists which grows dynamically. changing the size of numpy array will create a new array and delete the original .
### THe elements in a Numpy Array are required to be of the same data  type and that will be of the same size in memory.
### Numpy Arrays facilitate advanced mathematical and other types of operations on large number of data. Typically, such operations are executed more efficiently with less code that possible using python's built in sequences. 



In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [3]:
array=np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [4]:
type(array)

numpy.ndarray

In [5]:
np.array([[1,2,3],[4,5,6]])


array([[1, 2, 3],
       [4, 5, 6]])

## np.array() -> Creating he multidimentional arrays

### dtype parameter -> which can help us out with deciding about the size of the data we are going to store inside our array 

In [7]:
np.array([1,2,3,4,5], dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [8]:
np.array([7,8,9,10], dtype=np.int64)

array([ 7,  8,  9, 10])

In [10]:
np.array([11,13,14,15], dtype=float)

array([11., 13., 14., 15.])

In [11]:
np.array([11,13,14,15], dtype=bool)

array([ True,  True,  True,  True])

In [12]:
empty_list=[]
for i in range (16):
    empty_list.append(i)
    
empty_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [14]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
## arange() -> It helps us out with providing the values over a certain range

In [16]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
arange_data=np.arange(1 ,17)

In [23]:
arange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### np.reshape() -> It help us out with chnaging the shap of the array as per our needs

In [25]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [ ]:
## ones() -> np.ones() => Used in neural network -> Initialize the weight of the neurons in the neural network architecture

In [28]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
## zeros()

In [32]:
np.zeros((4,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## random() ->It helps us out with generrating any random values from 0 to 1 inside our matrix

In [37]:
np.random.random((3,4))

array([[0.94844668, 0.85364654, 0.10553516, 0.10994576],
       [0.66151499, 0.52572318, 0.18855681, 0.74399854],
       [0.00752744, 0.96912746, 0.65208648, 0.55877586]])

## Identity() -> it helps us about creting the matrix as a identity matrix (square Matrix -> Rows=coumns)

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## linspace() -> It makes sure that every value with the given range is going to have similar distance from each other

In [42]:
np.linspace(-10,10,6)

array([-10.,  -6.,  -2.,   2.,   6.,  10.])

## Attributes

# ndim -> ndim stands for n dimentions

In [43]:
arr = np.array([1,2,3])

In [44]:
arr

array([1, 2, 3])

In [45]:
arr.ndim

1

In [46]:
arrayy=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [48]:
arrayy.ndim

3

In [49]:
np.array([[1,2],[3,4]]).ndim

2

In [50]:
## shape -> It provides us with the idea about the rows, column in our dataset or in array

In [56]:
arrra=np.array([[1,2,3], [4,5,6],[7,8,9]])


In [57]:
arrra

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arrra.shape

(3, 3)

In [61]:
three=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [62]:
three

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [63]:
three.shape

(2, 2, 2)

In [64]:
## size -> Total number of elements present inside our dataset or array

In [65]:
array_elements=np.arange(5,57)


In [66]:
array_elements.size

52

In [68]:
np.array([[1,2],[3,4],[5,6]]).itemsize

8

In [69]:
np.array([[1,2],[3,4],[5,6]], dtype=np.int32).itemsize

4

In [70]:
## itemsize -> provides the idea about the size of a unique elements inside our array in bytes

In [71]:
## dtype ->> it provides us with the idea about the type of every item inside our array

In [72]:
np.array([[1,2,3],[4,5,6]]).dtype

dtype('int64')

## astype() -> it will be helping us out with figuring out the data type of the column in dataset in pandas and it will be used in numpy as well for getting the data type change or overall array 

In [5]:
array= np.arange(1,10).reshape(3,3)

In [6]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [8]:
type(array)

numpy.ndarray

In [9]:
array.dtype

dtype('int64')

In [10]:
array=array.astype('float64')

In [11]:
array.dtype

dtype('float64')

## Mathematical Operations in numpy

In [12]:
## Scalar Operations -> A scalar value operation will be done with the array or a numeric value

In [14]:
array=np.random.random((3,3))*100

In [15]:
np.round(array)

array([[74., 95., 42.],
       [90., 67.,  8.],
       [ 2., 43., 57.]])

In [16]:
array=array.astype('int32')


In [17]:
array


array([[74, 94, 41],
       [89, 67,  8],
       [ 1, 43, 56]], dtype=int32)

In [18]:
## Scalar Operations with our Matrix or Array

In [19]:
array+2

array([[76, 96, 43],
       [91, 69, 10],
       [ 3, 45, 58]], dtype=int32)

In [20]:
array-2

array([[72, 92, 39],
       [87, 65,  6],
       [-1, 41, 54]], dtype=int32)

In [21]:
array*2

array([[148, 188,  82],
       [178, 134,  16],
       [  2,  86, 112]], dtype=int32)

In [22]:
array/2

array([[37. , 47. , 20.5],
       [44.5, 33.5,  4. ],
       [ 0.5, 21.5, 28. ]])

In [23]:
## We can apply scalar operations with the array in  terms of arithmatic operations

In [24]:
array




array([[74, 94, 41],
       [89, 67,  8],
       [ 1, 43, 56]], dtype=int32)

In [25]:
array>60

array([[ True,  True, False],
       [ True,  True, False],
       [False, False, False]])

In [26]:
## Vector Operations -> Operations will be in between thre given number of matrices

In [27]:
arr1=np.arange(1,17).reshape(4,4)


In [28]:
arr2=np.arange(17,33).reshape(4,4)

In [29]:
arr1 + arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [30]:
arr2-arr1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [31]:
arr1*arr2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

##  Important functions in numpy for machine learning and data science

In [32]:
## max() - > It is going to used to calculate the max value inside a matrix or an array 
## Syntax of max() - > np.max(array)


In [33]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
maximum=np.max(arr1)

In [35]:
maximum

np.int64(16)

In [36]:
arr=np.round(np.random.random((4,4)) * 100).astype('int32')

In [37]:
arr

array([[30, 73, 22,  8],
       [ 3, 23,  7, 58],
       [79, 48, 17, 89],
       [82, 43, 36, 40]], dtype=int32)

## axis ->  it provides us with the idea about the any operation value inside a specific row or column or we can get a specific value row wise  or column wise.

## axis =0 -> column wise operation
## axis =1 -> row wise operation

In [53]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.max(arr, axis=0)

array([82, 73, 36, 89], dtype=int32)

In [40]:
np.max(arr, axis=1)

array([73, 58, 89, 82], dtype=int32)

In [ ]:
## min() ->  It will be used for calculating the minimum value from the matrix or array
## Syntax -> np.min(array)

In [42]:
arr


array([[30, 73, 22,  8],
       [ 3, 23,  7, 58],
       [79, 48, 17, 89],
       [82, 43, 36, 40]], dtype=int32)

In [43]:
np.min(arr)

np.int32(3)

In [44]:
np.min(arr, axis=0)

array([ 3, 23,  7,  8], dtype=int32)

In [45]:
np.min(arr, axis=1)

array([ 8,  3, 17, 36], dtype=int32)

In [46]:
arr=np.arange(1,11)

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
np.max(arr)

np.int64(10)

In [49]:
np.min(arr)

np.int64(1)

In [50]:
## sum() -> calculate the sum of all of the values of a given matrix

## Syntax for sum() -> np.sum()



In [54]:
arr= np.round(np.random.random((4,4))*100).astype('int32')

In [55]:
arr

array([[68, 16, 44, 21],
       [28, 97,  8, 51],
       [23, 70,  9, 15],
       [17, 25, 89, 58]], dtype=int32)

In [56]:
np.sum(arr)

np.int64(639)

In [57]:
np.sum(arr,0)

array([136, 208, 150, 145])

In [60]:
np.sum(arr,1) # row

array([149, 184, 117, 189])

In [61]:
## prod() -> It helps with calculating the product of all values inside the matrix
## Syntax -> np,prod()


In [62]:
arr

array([[68, 16, 44, 21],
       [28, 97,  8, 51],
       [23, 70,  9, 15],
       [17, 25, 89, 58]], dtype=int32)

In [63]:
np.prod(arr)

np.int64(6705993427280625664)

In [65]:
array=np.arange(1,10)

In [66]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.prod(array)

np.int64(362880)

In [ ]:
np.prod(arr, axis=1) # row wise

array([1005312, 1108128,  217350, 2193850])

In [ ]:
np.prod(arr, axis=0) # column wise

array([ 744464, 2716000,  281952,  931770])

## Statistical Functions in Numpy

In [70]:
## mean() -> syntax for mean() -> np.mean() -> mean of all values inside the array or matrix

In [71]:
arr


array([[68, 16, 44, 21],
       [28, 97,  8, 51],
       [23, 70,  9, 15],
       [17, 25, 89, 58]], dtype=int32)

In [72]:
np.mean(arr)

np.float64(39.9375)

In [73]:
np.mean(arr,axis=1) ## row

array([37.25, 46.  , 29.25, 47.25])

In [74]:
np.mean(arr,axis=0)

array([34.  , 52.  , 37.5 , 36.25])

In [75]:
## std() -> it provides with the standarddeviation of all values of the matrix or array

In [76]:
arr


array([[68, 16, 44, 21],
       [28, 97,  8, 51],
       [23, 70,  9, 15],
       [17, 25, 89, 58]], dtype=int32)

In [77]:
np.std(arr)

np.float64(27.983184124577388)

In [78]:
np.std(arr, axis=1)

array([20.65641547, 33.14362684, 24.04552973, 28.58649157])

In [79]:
np.std(arr, axis=0)

array([20.0124961 , 33.06811153, 33.07944981, 18.53881064])

In [80]:
## median() -> To calculate median of all values in the array or matrix
## syntax of median => np.median()

In [81]:
arr

array([[68, 16, 44, 21],
       [28, 97,  8, 51],
       [23, 70,  9, 15],
       [17, 25, 89, 58]], dtype=int32)

In [82]:
np.median(arr)

np.float64(26.5)

In [83]:
np.median(arr,axis=0)

array([25.5, 47.5, 26.5, 36. ])

In [84]:
np.median(arr, axis=1)

array([32.5, 39.5, 19. , 41.5])

In [85]:
## var -> it helps with calculating te variance of the values inside the array or matrix
## syntax -> np.var()

arr

array([[68, 16, 44, 21],
       [28, 97,  8, 51],
       [23, 70,  9, 15],
       [17, 25, 89, 58]], dtype=int32)

In [86]:
np.var(arr)

np.float64(783.05859375)

In [87]:
np.var(arr, axis=0)

array([ 400.5   , 1093.5   , 1094.25  ,  343.6875])

In [88]:
np.var(arr, axis=1) # row

array([ 426.6875, 1098.5   ,  578.1875,  817.1875])

## Trigonometric Functions

In [89]:
## sin() -> sin value for the value we are going to pass inside it  -> np.sin() 

In [90]:
np.sin(0)

np.float64(0.0)

In [91]:
np.sin(60)

np.float64(-0.3048106211022167)

In [92]:
np.tan(45)

np.float64(1.6197751905438615)

In [93]:
np.cos(45)

np.float64(0.5253219888177297)

In [95]:
## Dot product of matrices
## syntax for Dot Product -> np.dot(matrix1, matrix2)

In [100]:
matrix1= np.round(np.random.random((3,4))*100).astype('int32')
matrix2= np.round(np.random.random((4,3))*100).astype('int32')

In [102]:
matrix1

array([[ 7, 47, 23,  8],
       [15, 95, 11, 95],
       [36, 22, 80, 90]], dtype=int32)

In [103]:
matrix2

array([[58, 20, 59],
       [80, 44, 16],
       [93, 54,  5],
       [48, 34, 30]], dtype=int32)

In [104]:
np.dot(matrix1, matrix2)

array([[ 6689,  3722,  1520],
       [14053,  8304,  5310],
       [15608,  9068,  5576]], dtype=int32)

In [107]:
## log() -> To calculate the log of all values of our matrix

## Syntax of log() -> np.log()

In [108]:
matrix1

array([[ 7, 47, 23,  8],
       [15, 95, 11, 95],
       [36, 22, 80, 90]], dtype=int32)

In [109]:
np.log(matrix1)

array([[1.94591015, 3.8501476 , 3.13549422, 2.07944154],
       [2.7080502 , 4.55387689, 2.39789527, 4.55387689],
       [3.58351894, 3.09104245, 4.38202663, 4.49980967]])

In [110]:
## Exponential exp() ->  exponential of all values inside matrix
## syntax -> np.exp()

In [111]:
matrix1

array([[ 7, 47, 23,  8],
       [15, 95, 11, 95],
       [36, 22, 80, 90]], dtype=int32)

In [112]:
np.exp(matrix1)

array([[1.09663316e+03, 2.58131289e+20, 9.74480345e+09, 2.98095799e+03],
       [3.26901737e+06, 1.81123908e+41, 5.98741417e+04, 1.81123908e+41],
       [4.31123155e+15, 3.58491285e+09, 5.54062238e+34, 1.22040329e+39]])

## round() -> it helps with rounding off thr float values to its nearest possible integer value
## syntax of round() -> np.round()
## round off value of 1.7 is 2
## 1.3 is 1

In [116]:
arr=np.random.random((3,4))*100

In [117]:
arr

array([[80.45920473,  7.16400026, 91.06525331, 18.66216475],
       [74.26782808, 82.78611321, 56.42442439, 18.63737865],
       [84.016408  , 87.23874846, 45.23220037, 30.37542273]])

In [118]:
np.round(arr)

array([[80.,  7., 91., 19.],
       [74., 83., 56., 19.],
       [84., 87., 45., 30.]])

In [119]:
''' round() -> 1.6 ->2 1.3-> 1
ceil() ->1.6 -> 2 1.3 -> 2
floor() -> 1.6 -> 1 1.3 -> 1
'''

' round() -> 1.6 ->2 1.3-> 1\nceil() ->1.6 -> 2 1.3 -> 2\nfloor() -> 1.6 -> 1 1.3 -> 1\n'

In [120]:
## ceil() -> next correspoinding value ->np.ceil()

In [121]:
matrix1

array([[ 7, 47, 23,  8],
       [15, 95, 11, 95],
       [36, 22, 80, 90]], dtype=int32)

In [122]:
arr


array([[80.45920473,  7.16400026, 91.06525331, 18.66216475],
       [74.26782808, 82.78611321, 56.42442439, 18.63737865],
       [84.016408  , 87.23874846, 45.23220037, 30.37542273]])

In [123]:
np.ceil(arr)

array([[81.,  8., 92., 19.],
       [75., 83., 57., 19.],
       [85., 88., 46., 31.]])

In [124]:
# floor() -> privious value -> np.floor()

In [125]:
np.floor(arr)

array([[80.,  7., 91., 18.],
       [74., 82., 56., 18.],
       [84., 87., 45., 30.]])

In [126]:
## Transpose() -> It calculates the transpose of the given matrix
## syntax -> np.transpose(arr)   or arr.T

## trabspose -> (i,j) -> (j,i)  -> (3,4)  -> T  -> (4,3)

In [129]:
arr=np.arange(1,13).reshape(3,4)

In [130]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [131]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [132]:
np.transpose(arr)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [133]:
## Ravel() -> np.ravel() -> convert nd array into 1d array


In [134]:
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [135]:
arr.ndim

2

In [136]:
np.ravel(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Indexing and Slicing in numpy

In [137]:
## Indexing -> lists[,size-1] -> to have the access over the values

In [138]:
arr=np.round(np.random.random((5,5))* 100).astype('int32')

In [139]:
arr

array([[57, 24, 20, 18, 93],
       [27, 18,  8, 69, 41],
       [30, 95,  2, 74,  5],
       [ 0, 49, 53,  9, 55],
       [52, 24, 81, 48, 70]], dtype=int32)

In [140]:
arr1=np.arange(1,10)

In [141]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
arr1[6]

np.int64(7)

In [143]:
arr

array([[57, 24, 20, 18, 93],
       [27, 18,  8, 69, 41],
       [30, 95,  2, 74,  5],
       [ 0, 49, 53,  9, 55],
       [52, 24, 81, 48, 70]], dtype=int32)

In [ ]:
## Indexing in 2d array -> [row, column]
## Indexing in 3d array -> [z-axis, x-axis, y-axis]

In [144]:
arr[4,4]

np.int32(70)

In [145]:
arrr=np.arange(1,9).reshape(2,2,2)

In [146]:
arrr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [148]:
arrr[1,0,1]

np.int64(6)

In [149]:
arrr[0,1,0]

np.int64(3)

In [150]:
arrr[1,1,0]

np.int64(7)

In [151]:
## Slicing -> similar approch like list[:]
## 2d array -> [row1:row2, col1:col2]

In [152]:
arrr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [153]:
arr

array([[57, 24, 20, 18, 93],
       [27, 18,  8, 69, 41],
       [30, 95,  2, 74,  5],
       [ 0, 49, 53,  9, 55],
       [52, 24, 81, 48, 70]], dtype=int32)

In [158]:
arr[:,2]

array([20,  8,  2, 53, 81], dtype=int32)

In [159]:
arr[0, :]

array([57, 24, 20, 18, 93], dtype=int32)

In [ ]:
arr[2:4, 3:]

array([[74,  5],
       [ 9, 55]], dtype=int32)

In [162]:
arr[2:,1:4]

array([[95,  2, 74],
       [49, 53,  9],
       [24, 81, 48]], dtype=int32)

In [163]:
## Iterating over an array

In [164]:
array= np.arange(1,10)

In [166]:
for i in array:
    print(i)

1
2
3
4
5
6
7
8
9


In [167]:
array=np.arange(1,17).reshape(4,4)

In [168]:
for i in array:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [169]:
array=np.arange(1,28).reshape(3,3,3)
    

In [170]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [171]:
for i in array:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [172]:
## nditer() -> It can help us out with iterating over evey value in a nd array

In [173]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [174]:
for i in np.nditer(array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [175]:
## 1D array -> value by value iteration
## 2D array -> Row by row on iteration
## 3D array -> 2D array by 2D array iteration

In [ ]:
## Stacking and Splitting in arrays: -> Size of the arrays must be same

In [177]:
## Stacking -> Joining the arrays together
## Horizontal Staking ->  Row by row joining is done -> hstack()
## Vertical Staking -> column by column joining done ->vstack()

In [178]:
array1= np.arange(1,13).reshape(3,4)

In [179]:
array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [180]:
array2=np.arange(13,25).reshape(3,4)

In [181]:
array2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [182]:
horizontal_array=np.hstack((array1,array2))

In [183]:
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [186]:
vartical_array=np.vstack((array1,array2))

In [187]:
vartical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [188]:
## Harizontal Split -->  np.hsplit(array,number of parts you want your array to be splitted at)
## Vartical Split --> np.vsplit(array,number of parts)

In [189]:
np.hsplit(vartical_array,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [190]:
np.vsplit(vartical_array,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [191]:
np.vsplit(vartical_array,3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [192]:
np.vsplit(vartical_array,4)

ValueError: array split does not result in an equal division